import { supabase } from "@/lib/supabase";

export interface AuditParams {
  action: "create" | "update" | "delete" | "login" | "assign" | "revoke";
  actor_id: string;      // User performing the action
  actor_role: string;    // Role name of the user
  entity_type: string;   // 'patient', 'staff', 'inventory', 'role', etc.
  entity_id: string;     // Primary key or identifying name of the modified object
  before_data?: any;     // Previous state (optional)
  after_data?: any;      // New state (optional)
}

/**
 * Log an audit action to the centralized generic `audit_log` table.
 * Uses the service role client by default so it never fails due to RLS.
 */
export async function logAudit({
  action,
  actor_id,
  actor_role,
  entity_type,
  entity_id,
  before_data = null,
  after_data = null,
}: AuditParams): Promise<void> {
  // Fire and forget, but catch errors in server logs
  supabase
    .from("audit_log")
    .insert({
      action,
      actor_id,
      actor_role,
      entity_type,
      entity_id,
      before_data,
      after_data,
      // timestamp is automatically generated by DB's default now()
    })
    .then(({ error }) => {
      if (error) {
        console.error("Failed to insert audit log:", error.message);
      }
    });
}
